# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 src tests --max-line-length=100

      - name: Train model smoke test
        run: |
          python src/train.py --seed 42 --model random_forest
          cat metrics.json
          cat metrics_v0.2.json
          cat metrics_v0.3.json

      - name: Run tests
        run: |
          pytest -q --disable-warnings

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            model/
            metrics.json
            metrics_v0.2.json
            metrics_v0.3.json