# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python src/train.py --seed 42

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker build -t $IMAGE_NAME .

      - name: Test Docker image locally
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker run -d -p 8000:8000 --name test_container $IMAGE_NAME
          sleep 15
          curl -f http://localhost:8000/health
          docker stop test_container
          docker rm test_container

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker push $IMAGE_NAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Docker Image
            
            Pull the image:
            ```bash
            docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ```
            
            Run the container:
            ```bash
            docker run -d -p 8000:8000 ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ```
            
            ## Health Check
            ```bash
            curl http://localhost:8000/health
            ```