# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/assignment-3
      IMAGE_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python src/train.py --seed 42 --model ridge

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Test Docker image locally
        run: |
          docker run -d -p 8000:8000 --name test_container ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          sleep 15
          curl -f http://localhost:8000/health
          docker stop test_container
          docker rm test_container

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.IMAGE_TAG }}
          name: Release ${{ env.IMAGE_TAG }}
          body: |
            ## Docker Image
            
            Pull the image:
            ```bash
            docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ```
            
            Run the container:
            ```bash
            docker run -d -p 8000:8000 ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ```
            
            ## Health Check
            ```bash
            curl http://localhost:8000/health
            ```